sudo: false
os:
  - linux
language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'
install:
  - python -m pip install -r dev_requirements.txt
  - make build
  - python -m pip uninstall --yes -r dev_requirements.txt
  - python -m pip install --upgrade tox tox-travis
  - python -m pip freeze
script: tox
jobs:
  # See https://github.com/pyload/pyload/blob/458fa33b42/.travis.yml
  # for a workaround for testing on macOS with Travis
  include:
    - name: "macOS tests"
      os: osx
      language: sh
      env:
        - HOMEBREW_NO_INSTALL_CLEANUP=1
        - HOMEBREW_NO_ANALYTICS=1
      before_cache:
        - rm -f "$HOME/Library/Caches/pip/log/debug.log"
      cache:
        directories:
          - "$HOME/Library/Caches/pip"
      addons:
        homebrew:
          update: true
          packages: python3
      before_install:
        - python -m pip install --upgrade virtualenv
        - virtualenv -p python --system-site-packages "$HOME/venv"
        - source "$HOME/venv/bin/activate"
notifications:
  email: false
  slack:
    rooms:
      secure: rxQsNRK9XBkBV0pdYuJG+tsN2tky+JUEF5ayDIUAzSaPeB//VVNNofJhcmfNgG1WiEEi6fe0dR/Y6UDsoVyQrbCHO2q2bIVQp6A/63vgz3DcVQzMahB/QVwte7gy02nLf6rS2g3VetVXrTW6OO4Cv7NQrQb58biVFx/yBtQ3qzI=
    on_success: never
    on_failure: always