name: Sdist
run-name: Make a source distribution

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:

make_sdist:
  name: Make SDist
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v3
    with:
      fetch-depth: 0

  - name: Build SDist
    run: pipx run build --sdist

  - uses: actions/upload-artifact@v3
    with:
      path: dist/*.tar.gz
